# Generated by Django 5.2.8 on 2025-11-30 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['restaurant_id']},
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='restaurants.restaurant')),
            ],
            options={
                'db_table': 'donation',
                'ordering': ['donation_id'],
            },
        ),
    ]
