# Generated by Django 5.2.8 on 2025-12-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_alter_dropoff_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='dropoff_time',
            field=models.TimeField(),
        ),
    ]
