# Generated by Django 5.2.8 on 2025-12-15 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_fix_dropoff_time_data'),
        ('delivery', '0009_alter_delivery_dropoff_time'),
    ]

    operations = [
    ]
