# Generated by Django 5.2.8 on 2025-12-04 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fooditem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('impact_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('meals_saved', models.FloatField()),
                ('weight_saved_kg', models.FloatField()),
                ('co2_reduced_kg', models.FloatField()),
                ('impact_date', models.DateField(auto_now_add=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='fooditem.fooditem')),
            ],
            options={
                'db_table': 'impact_record',
            },
        ),
    ]
