# Generated by Django 5.2.8 on 2025-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('chain_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chain_name', models.CharField(max_length=100)),
            ],
        ),
    ]
