# Generated by Django 5.2.8 on 2025-12-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_alter_donation_status'),
        ('users', '0005_alter_admin_user_alter_deliverystaff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='users.user'),
        ),
    ]
