# Generated by Django 5.2.8 on 2025-12-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation_request', '0004_merge_20251214_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='created_by',
        ),
    ]
